# Generated by Django 3.1.4 on 2020-12-30 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='add_product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30)),
                ('product_price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('tittle', models.CharField(max_length=50)),
                ('images', models.ImageField(upload_to='pics/products/')),
            ],
        ),
    ]
