# Generated by Django 3.1.4 on 2020-12-30 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_product',
            name='product_price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
