# Generated by Django 3.1.4 on 2020-12-30 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_product', '0002_auto_20201230_1253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_product',
            old_name='images',
            new_name='image',
        ),
    ]
