# Generated by Django 3.1.4 on 2021-01-02 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_product', '0006_auto_20201230_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_product',
            name='image',
        ),
    ]
